### PR TITLE
Fix dialog parameters to avoid duplicate keywords

### PR DESCRIPTION
**Pull request by imagejan**
See http://imagej.1557.x6.nabble.com/Colocalization-test-and-Macro-tp5016660.html

### CODE REVIEW

**Comment by ctrueden** [comment]
Awesome, thanks!

**Comment by chalkie666** [comment]
Hi Jan

Thanks for those fixes!

But just to remind you the maths in the coloc test Plugin is not what us in
the costes paper. It's only a while noise approximation and doesn't
scramble the image data. Coloc 2 does it properly.
Cheers

D

**Comment by ctrueden** [comment]
@chalkie666 Indeed, this was just a technical fix. It would be great if you could reply to the email thread on the list reminding the user that the `Colcalisation_Test` plugin is highly suboptimal.

**Comment by chalkie666** [comment]
Will do!

D

**Pull request merged**
