### PR TITLE
Fix issue33

### PR DESCRIPTION
**Pull request by chalkie666**
fixes issue #33 and also augments the results output which get unique roi/mask IDs for each coloc job that is run, and remove the frightening -1 result value and change to Done.

### CODE REVIEW

**Comment by chalkie666** [comment]
@tomka ok to merge?

**Comment by tomka** [comment]
Sorry for the delay, was sick the last week, but will have a look at it today.

**Comment by tomka** [comment]
Indeed, the `DataContainer` constructors should share more code. Alternatively to what you did in 897fd4b, you could have just changed the call to `DataContainer` to include the "Ch1_" and "Ch2_" prefixes. This way you would have probably needed to change less code. Anyway, all the commits look fine and I'll merge it in.

**Comment by chalkie666** [comment]
Me too.
Stupid viruses.
D

**Pull request merged**
