### PR TITLE
Add and default to regression pattern used by Costes

### PR DESCRIPTION
**Pull request by tomka**
This pull request adds support for different regression patterns. It also adds an alternative to the current bisection method: a simple regression that decrements values one by one, just as it is used in the Costes paper. Since this is what people are likely to expect, it is now the default. The faster bisection method is still available, but has to be selected by the user.

If there are no changes requested, I'll merge this in a couple of days into master. The pull request is only used for documentation and to allow discussion about this change.

### CODE REVIEW

**Comment by ctrueden** [comment]
I can't comment on the technical approach, since I'm ignorant about colocalization. But the code quality looks great—nice patches. And in general, I am a fan of doing [what people expect, instead of what will surprise them](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by tomka** [comment]
I should be able to go through this again next week and then finally merge this in.

**Comment by tomka** [comment]
I looked through everything again, think all the changes are alright and will merge this.

**Comment by chalkie666** [comment]
great! thanks @tomka !

**Pull request merged**
